---
host: "https://<your-domain-here>"
yield_dir: "yield"
#secret: "<optional-access-secret>"
#api:
#  language: NO        # NO, SE, FI (default: NO)
#  region: NO          # NO, SE, FI (default: NO)
#  request_timeout: 30.0
#  disable_credentials_storage: false
#  max_concurrent_downloads: 3
auth:
  email: "<your-email-here>"
  password: "<your-password-here>"
podcasts:
#  papaya:
#    feed_name: "papayayaya"
#    most_recent_episodes_limit: 50
#  gi-meg-alle-detaljene:
#  konspirasjonspodden:
...
